{{- if .Values.enabled }}
{{- if .Values.volume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wg-easy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.volume.annotations | nindent 4 }}
spec:
  {{- if .Values.volume.className }}
  storageClassName: {{ .Values.volume.className }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.volume.size }}
{{- end }}
{{- end }}